"""Pydantic schemas for customer CRUD (Phase 4).

A ``Customer`` is an agent-owned trading account: broker credentials plus a
single ISIN/side pair. Agents create them via their dashboard; admins can
create / edit / delete them on behalf of any agent. The render layer
(Phase 4 also) turns one row into a ``[section_name]`` block inside the
``config.ini`` that the SSH layer ships out to a server.

Secret hygiene
--------------
:attr:`CustomerCreate.password` and :attr:`CustomerUpdate.password` are
write-only — they are accepted on the form but MUST never appear on an
outbound :class:`CustomerOut`. The model column ``password_enc`` (Fernet
ciphertext) is also deliberately excluded from :class:`CustomerOut` so it
can't leak via a JSON response, audit-log payload, or a debug template
dump.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

# The ten Iranian brokers supported by SellerMarket today. Kept in sync with
# :class:`SellerMarket.broker_enum.BrokerCode` — if a broker is added there
# this tuple (and the ``Broker`` ``Literal``) must be widened too.
BROKERS = (
    "gs",
    "bbi",
    "shahr",
    "ib",
    "karamad",
    "tejarat",
    "ebb",
    "hbc",
    "rabin",
    "ayandeh",
)

# Pydantic v2 uses the ``Literal`` directly for both validation and JSON-schema
# generation. We duplicate the values here rather than build it from
# ``BROKERS`` because ``Literal[*tuple]`` unpacking is a 3.11+ syntax that some
# tooling (mypy, ruff) still chokes on intermittently.
Broker = Literal[
    "gs",
    "bbi",
    "shahr",
    "ib",
    "karamad",
    "tejarat",
    "ebb",
    "hbc",
    "rabin",
    "ayandeh",
]

# Trade direction. The downstream bot encodes Buy=1 / Sell=2; the DB has a
# CHECK constraint that enforces the same. We surface that contract through
# the schema so pydantic refuses anything out of range at the HTTP boundary
# (before it can hit the DB and become an opaque IntegrityError).
Side = Literal[1, 2]


def _validate_isin(value: str) -> str:
    """ISIN sanity — ASCII alphanumeric, length <= 32, uppercased.

    The Tehran-stock-exchange ISIN format is ``IRO<XXXXXXXX>`` for stocks, but
    we accept any family that fits the shape so the field is future-proof
    against new TSE instrument types. The validator just enforces shape so
    nothing weird ends up in a section name or a ``config.ini`` line later
    (a stray space, hyphen, or NUL byte would break the INI parser on the
    other side).
    """
    if not value:
        raise ValueError("isin must not be empty")
    if not value.isascii() or not value.isalnum():
        raise ValueError("isin must be ASCII alphanumeric (no spaces / punctuation)")
    if len(value) > 32:
        raise ValueError("isin too long")
    return value.upper()


class CustomerCreate(BaseModel):
    """What agents (and admins) submit on the create form.

    ``section_name`` is auto-generated by the service layer once the row has
    been flushed and the DB has assigned an ``id`` — see
    :func:`app.services.customers._build_section_name`. It is therefore NOT
    accepted on input; trying to override it would just be silently ignored.
    """

    display_name: str = Field(min_length=1, max_length=255)
    broker: Broker
    isin: str = Field(min_length=1, max_length=32)
    side: Side
    username: str = Field(min_length=1, max_length=255)
    password: str = Field(min_length=1, max_length=512)
    comment: Optional[str] = Field(default=None, max_length=1024)

    @field_validator("isin")
    @classmethod
    def _check_isin(cls, v: str) -> str:
        return _validate_isin(v)


class CustomerDuplicate(BaseModel):
    """Agent UX: clone an existing customer with a different ISIN.

    The new row carries over the source's broker, username, side, and
    encrypted password (so the agent doesn't have to re-type credentials they
    already entered). Only the ISIN (and optionally a new display name)
    changes. The clone starts unassigned (``assignment_status='pending'``).
    """

    isin: str = Field(min_length=1, max_length=32)
    # If absent, the service layer defaults to ``"<source.display_name> (<new_isin>)"``.
    new_display_name: Optional[str] = Field(default=None, max_length=255)

    @field_validator("isin")
    @classmethod
    def _check_isin(cls, v: str) -> str:
        return _validate_isin(v)


class CustomerUpdate(BaseModel):
    """Partial update with optimistic locking.

    ``version`` is REQUIRED for every update — the caller must echo the
    version they read from the row. A mismatch raises
    :class:`app.services.customers.OptimisticLockError` which the router
    translates to HTTP 409. This prevents two admins (or an admin and an
    agent) racing on the same row from silently overwriting each other.

    Every other field is optional; only the explicitly-set ones are touched
    on the underlying row. ``password=None`` means "keep the current
    password", not "set the password to empty" — to clear a password the
    caller would have to send a non-empty placeholder, which is intentional
    (we never want a blank credential reaching the SSH-shipped ``config.ini``).
    """

    display_name: Optional[str] = Field(default=None, min_length=1, max_length=255)
    broker: Optional[Broker] = None
    isin: Optional[str] = Field(default=None, min_length=1, max_length=32)
    side: Optional[Side] = None
    username: Optional[str] = Field(default=None, min_length=1, max_length=255)
    # ``password`` is only set when the caller chose to rotate it. The service
    # layer Fernet-encrypts the value into ``password_enc``.
    password: Optional[str] = Field(default=None, min_length=1, max_length=512)
    comment: Optional[str] = Field(default=None, max_length=1024)
    enabled: Optional[bool] = None
    version: int = Field(..., ge=1)

    @field_validator("isin")
    @classmethod
    def _check_isin(cls, v: Optional[str]) -> Optional[str]:
        return None if v is None else _validate_isin(v)


class CustomerOut(BaseModel):
    """Outbound representation of a Customer row.

    Deliberately omits ``password_enc`` (the Fernet ciphertext) so we cannot
    accidentally leak it via JSON responses, audit-log payloads, or template
    dumps. The render layer reads the ciphertext directly off the ORM row,
    never through this schema.
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    agent_id: UUID
    server_id: Optional[UUID]
    stack_id: Optional[UUID]
    assignment_status: str
    display_name: str
    section_name: str
    username: str
    broker: str
    isin: str
    side: int
    enabled: bool
    comment: Optional[str]
    version: int
    created_at: datetime
    updated_at: datetime
