"""Pydantic schemas for TradeInstruction CRUD.

A TradeInstruction is "trade ISIN X on side Y for Customer Z". One
Customer can have many. Created via the customer detail page; the
service layer auto-generates the ``section_name`` from the parent
customer's broker + agent id + the new trade_instruction id.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


# Trade direction. The downstream bot encodes Buy=1 / Sell=2; the DB has a
# CHECK constraint that enforces the same. We surface that contract through
# the schema so pydantic refuses anything out of range at the HTTP boundary
# (before it can hit the DB and become an opaque IntegrityError).
Side = Literal[1, 2]


def _validate_isin(value: str) -> str:
    """ISIN sanity — ASCII alphanumeric, length <= 32, uppercased.

    The Tehran-stock-exchange ISIN format is ``IRO<XXXXXXXX>`` for stocks, but
    we accept any family that fits the shape so the field is future-proof
    against new TSE instrument types. The validator just enforces shape so
    nothing weird ends up in a section name or a ``config.ini`` line later
    (a stray space, hyphen, or NUL byte would break the INI parser on the
    other side).
    """
    if not value:
        raise ValueError("isin must not be empty")
    if not value.isascii() or not value.isalnum():
        raise ValueError("isin must be ASCII alphanumeric (no spaces / punctuation)")
    if len(value) > 32:
        raise ValueError("isin too long")
    return value.upper()


class TradeInstructionCreate(BaseModel):
    """What a "+ Add trade" form submits.

    ``section_name`` is auto-generated by the service layer once the row
    has been flushed (mirroring the old Customer pattern).
    """

    isin: str = Field(min_length=1, max_length=32)
    side: Side
    comment: Optional[str] = Field(default=None, max_length=1024)

    @field_validator("isin")
    @classmethod
    def _check_isin(cls, v: str) -> str:
        return _validate_isin(v)


class TradeInstructionUpdate(BaseModel):
    """Partial update with optimistic locking.

    Same shape as the Customer update — ``version`` REQUIRED, every other
    field optional. ``enabled=False`` disables only this one trade, not
    the entire Customer.
    """

    isin: Optional[str] = Field(default=None, min_length=1, max_length=32)
    side: Optional[Side] = None
    comment: Optional[str] = Field(default=None, max_length=1024)
    enabled: Optional[bool] = None
    version: int = Field(..., ge=1)

    @field_validator("isin")
    @classmethod
    def _check_isin(cls, v: Optional[str]) -> Optional[str]:
        return None if v is None else _validate_isin(v)


class TradeInstructionOut(BaseModel):
    """Outbound representation of a TradeInstruction row.

    No secrets to omit — all fields are safe to expose.
    """

    model_config = ConfigDict(from_attributes=True)

    id: UUID
    customer_id: UUID
    isin: str
    side: int
    section_name: str
    enabled: bool
    comment: Optional[str]
    version: int
    created_at: datetime
    updated_at: datetime
