"""Hermetic tests for :mod:`runtime_config` — the bot's DB-pushed [runtime] reader.

No network. A temp config.ini is written and pointed at via the ``CONFIG_INI``
env var; the monotonic clock is injected (``runtime_config._clock``) so TTL
behaviour is deterministic. The reader's contract:

* missing file / missing [runtime] / empty value  -> caller's hardcoded fallback;
* a value is adopted ONLY from a sentinel-terminated file (torn-write guard,
  same ``# auto-sell-config-end`` signal the auto-sell monitor trusts);
* a ``%`` anywhere in the file never raises (RawConfigParser, no interpolation);
* call-time reads with an mtime+TTL cache so long-running processes pick up a
  pushed change within ~TTL and per-run subprocesses read fresh.
"""
from __future__ import annotations

import os

import pytest

import runtime_config

SENTINEL = "# auto-sell-config-end"


def _write(path, runtime_lines=None, *, sentinel=True, extra="", mtime_ns=None):
    """Write a config.ini-shaped file. ``runtime_lines`` is a dict for [runtime]."""
    parts = ["# Generated by mgmt_ui — do not edit by hand.", ""]
    if runtime_lines is not None:
        parts.append("[runtime]")
        for k, v in runtime_lines.items():
            parts.append(f"{k} = {v}")
        parts.append("")
    if extra:
        parts.append(extra)
        parts.append("")
    if sentinel:
        parts.append(SENTINEL)
    path.write_text("\n".join(parts), encoding="utf-8")
    if mtime_ns is not None:
        os.utime(path, ns=(mtime_ns, mtime_ns))


@pytest.fixture(autouse=True)
def _isolate(monkeypatch, tmp_path):
    cfg = tmp_path / "config.ini"
    monkeypatch.setenv("CONFIG_INI", str(cfg))
    runtime_config.reset_cache()
    yield cfg
    runtime_config.reset_cache()


# --------------------------------------------------------------------------
# fallbacks
# --------------------------------------------------------------------------

def test_missing_file_returns_fallback(_isolate):
    # CONFIG_INI points at a path that doesn't exist yet.
    assert runtime_config.get("ephoenix_md_host", "marketdatagw") == "marketdatagw"


def test_no_runtime_section_returns_fallback(_isolate):
    _write(_isolate, runtime_lines=None, extra="[a1_cust_bbi_IRO1]\nusername = x")
    assert runtime_config.get("ephoenix_md_host", "marketdatagw") == "marketdatagw"


def test_empty_value_falls_back(_isolate):
    _write(_isolate, {"ephoenix_md_host": ""})
    assert runtime_config.get("ephoenix_md_host", "marketdatagw") == "marketdatagw"


# --------------------------------------------------------------------------
# reading values
# --------------------------------------------------------------------------

def test_reads_runtime_value(_isolate):
    _write(_isolate, {"ephoenix_md_host": "newmdgw"})
    assert runtime_config.get("ephoenix_md_host", "marketdatagw") == "newmdgw"


def test_typed_getters(_isolate):
    _write(_isolate, {
        "exir_fallback_buy_fee": "0.0042",
        "auto_sell_confirm_secs": "8",
        "watch_flag": "yes",
        "ocr_service_url": "http://a:1, http://b:2",
    })
    assert runtime_config.get_float("exir_fallback_buy_fee", 0.005) == pytest.approx(0.0042)
    assert runtime_config.get_int("auto_sell_confirm_secs", 5) == 8
    assert runtime_config.get_bool("watch_flag", False) is True
    assert runtime_config.get_list("ocr_service_url") == ["http://a:1", "http://b:2"]


def test_typed_getters_fall_back_on_garbage(_isolate):
    _write(_isolate, {"auto_sell_confirm_secs": "not-a-number"})
    assert runtime_config.get_int("auto_sell_confirm_secs", 5) == 5


def test_get_bool_falsey(_isolate):
    _write(_isolate, {"flag": "0"})
    assert runtime_config.get_bool("flag", True) is False


def test_get_list_missing_returns_default(_isolate):
    _write(_isolate, {"other": "x"})
    assert runtime_config.get_list("ocr_service_url", ["fallback"]) == ["fallback"]


def test_snapshot_returns_section_dict(_isolate):
    _write(_isolate, {"ephoenix_domain": "ephoenix.ir", "ib_md_host": "mdapi"})
    snap = runtime_config.snapshot()
    assert snap["ephoenix_domain"] == "ephoenix.ir"
    assert snap["ib_md_host"] == "mdapi"


# --------------------------------------------------------------------------
# %-safety (the configparser interpolation hazard)
# --------------------------------------------------------------------------

def test_percent_in_values_never_raises(_isolate):
    # A [runtime] value AND a customer-section password both carrying % must not
    # blow up the RawConfigParser read (default ConfigParser would raise).
    _write(
        _isolate,
        {"endpoint_ib_order": "https://x/y?a=%20b"},
        extra="[a1_cust_bbi_IRO1]\nusername = u\npassword = p%ss",
    )
    assert runtime_config.get("endpoint_ib_order", "") == "https://x/y?a=%20b"


def test_escaped_percent_is_unescaped(_isolate):
    # The renderer %%-escapes literal % so the bot's interpolating readers don't
    # choke; runtime_config recovers the literal value.
    _write(_isolate, {"endpoint_ib_order": "https://x/y?a=%%20b"})
    assert runtime_config.get("endpoint_ib_order", "") == "https://x/y?a=%20b"


# --------------------------------------------------------------------------
# sentinel / torn-write gate
# --------------------------------------------------------------------------

def test_untrusted_file_without_sentinel_is_ignored_then_adopted(_isolate, monkeypatch):
    now = [1000.0]
    monkeypatch.setattr(runtime_config, "_clock", lambda: now[0])
    # Torn write: has [runtime] but NO sentinel -> keep fallback.
    _write(_isolate, {"ephoenix_md_host": "torn"}, sentinel=False, mtime_ns=1_000_000_000)
    assert runtime_config.get("ephoenix_md_host", "marketdatagw") == "marketdatagw"
    # Completed write: sentinel present, newer mtime -> adopt after TTL.
    _write(_isolate, {"ephoenix_md_host": "good"}, sentinel=True, mtime_ns=2_000_000_000)
    now[0] += runtime_config._TTL_S + 1
    assert runtime_config.get("ephoenix_md_host", "marketdatagw") == "good"


# --------------------------------------------------------------------------
# mtime + TTL caching / refresh
# --------------------------------------------------------------------------

def test_change_within_ttl_serves_cache(_isolate, monkeypatch):
    now = [1000.0]
    monkeypatch.setattr(runtime_config, "_clock", lambda: now[0])
    _write(_isolate, {"ephoenix_md_host": "first"}, mtime_ns=1_000_000_000)
    assert runtime_config.get("ephoenix_md_host", "x") == "first"
    # File changes, but TTL has not elapsed -> still serves the cached value.
    _write(_isolate, {"ephoenix_md_host": "second"}, mtime_ns=2_000_000_000)
    now[0] += runtime_config._TTL_S / 2
    assert runtime_config.get("ephoenix_md_host", "x") == "first"


def test_refresh_after_ttl_picks_up_change(_isolate, monkeypatch):
    now = [1000.0]
    monkeypatch.setattr(runtime_config, "_clock", lambda: now[0])
    _write(_isolate, {"ephoenix_md_host": "first"}, mtime_ns=1_000_000_000)
    assert runtime_config.get("ephoenix_md_host", "x") == "first"
    _write(_isolate, {"ephoenix_md_host": "second"}, mtime_ns=2_000_000_000)
    now[0] += runtime_config._TTL_S + 1
    assert runtime_config.get("ephoenix_md_host", "x") == "second"
