"""Renderer for the per-agent ``docker-compose.yml``.

Constraints baked in by the Phase 3 plan:

* Single service ``trading-bot`` — no OCR sidecar, no telegram bot.
* No host ports — agent stacks are accessed only by the OCR/bot internals.
* Project name ``sm-agent-<agent_uuid>`` keeps each stack isolated from
  siblings and from the existing root-level deployment at
  ``/root/seller-market/``.
* The container ``command:`` override bypasses ``simple_config_bot.py``
  entirely (that script crashes on an invalid/empty ``TELEGRAM_BOT_TOKEN``)
  and runs only the scheduler. ``python -u`` keeps ``docker logs`` live.

The ``command:`` is emitted as YAML **list (exec) form** rather than a
string — string form goes through ``/bin/sh -c "…"`` and the nested
``"…"`` / ``'…'`` in the Python expression get mangled by shell quoting.
List form passes argv directly to the container with zero shell parsing,
which is the only reliable way to ship a complex ``python -c`` payload.
"""

from __future__ import annotations

import json

import yaml

from app.services.rendering import StackRenderContext

# The Python expression the container runs. Kept as a single string so the
# JSON encoder handles its quoting; rendered into the YAML list form
# alongside ``python -u -c`` so docker compose executes it via argv with
# no shell interpolation.
_SCHEDULER_BOOTSTRAP = (
    "import logging,sys; "
    "logging.basicConfig(level=logging.INFO,stream=sys.stdout); "
    "from scheduler import JobScheduler; "
    "JobScheduler('/app/scheduler_config.json').run()"
)


def render_compose_yaml(ctx: StackRenderContext) -> str:
    """Render ``docker-compose.yml`` for an agent stack.

    Hand-formatted (not ``yaml.safe_dump``) for readability and deterministic
    field ordering — the shape is fixed and we never round-trip our own
    output. We *do* parse the result with ``yaml.safe_load`` at the end as a
    cheap sanity check to catch typos before SFTP'ing it to a server.
    """
    project = f"sm-agent-{ctx.agent_id}"
    stack_dir = f"{ctx.server_base_dir.rstrip('/')}/{ctx.agent_id}"
    # #110 auto-sell (opt-in): when ``bot_market_data_url`` is set, run
    # ``bot_entrypoint.py`` (scheduler bg-thread + the auto-sell monitor) and pass
    # MARKET_DATA_URL so the monitor consumes the shared WS queue feed. When it's
    # empty (default) we keep the byte-identical scheduler-only ``python -c`` so
    # existing stacks render exactly as before. ``bot_entrypoint`` itself is
    # backward-compatible (scheduler-only when no armed instructions / no URL).
    if ctx.bot_market_data_url:
        bot_command = json.dumps(["python", "-u", "bot_entrypoint.py"], ensure_ascii=False)
    else:
        bot_command = json.dumps(["python", "-u", "-c", _SCHEDULER_BOOTSTRAP], ensure_ascii=False)

    env_lines = [
        f"      - TZ={ctx.tz}",
        f"      - OCR_SERVICE_URL={ctx.ocr_service_url}",
    ]
    if ctx.bot_market_data_url:
        env_lines.append(f"      - MARKET_DATA_URL={ctx.bot_market_data_url}")
    environment = "\n".join(env_lines)

    rendered = f"""# Generated by mgmt_ui — do not edit by hand.
# Project: {project}
# Stack dir: {stack_dir}
name: {project}

services:
  trading-bot:
    image: {ctx.agent_image_tag}
    container_name: sm-agent-{ctx.agent_id}-bot
    restart: unless-stopped
    # Lets the bot reach its OWN host's services from inside the container —
    # specifically a host-local OCR published on the host (HA plan WS1). A
    # comma-separated OCR_SERVICE_URL can then list ``host.docker.internal:18080``
    # (this host's local OCR) first and fail over to the shared one. Harmless
    # when unused. Requires Docker 20.10+ (the whole fleet is well past that).
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
{environment}
    command: {bot_command}
    volumes:
      - ./config.ini:/app/config.ini
      - ./scheduler_config.json:/app/scheduler_config.json
      - ./locust_config.json:/app/locust_config.json
      - ./logs:/app/logs
      - ./order_results:/app/order_results
      - ./.cache:/app/.cache
      - ./run_results:/app/run_results
      - ./trading_bot.log:/app/trading_bot.log
      - ./cache_warmup.log:/app/cache_warmup.log
"""

    # Cheap sanity check — catches a stray brace / wrong indent before we
    # SFTP this into production. Failure here is a renderer bug, not a
    # user-input bug, so an AssertionError is the right signal.
    parsed = yaml.safe_load(rendered)
    assert isinstance(parsed, dict) and "services" in parsed, (
        "render_compose_yaml produced invalid YAML"
    )
    return rendered
