"""Renderer for the per-agent ``docker-compose.yml``.

Constraints baked in by the Phase 3 plan:

* Single service ``trading-bot`` — no OCR sidecar, no telegram bot.
* No host ports — agent stacks are accessed only by the OCR/bot internals.
* Project name ``sm-agent-<agent_uuid>`` keeps each stack isolated from
  siblings and from the existing root-level deployment at
  ``/root/seller-market/``.
* The container ``command:`` override bypasses ``simple_config_bot.py``
  entirely (that script crashes on an invalid/empty ``TELEGRAM_BOT_TOKEN``)
  and runs only the scheduler. ``python -u`` keeps ``docker logs`` live.
"""

from __future__ import annotations

import yaml

from app.services.rendering import StackRenderContext


def render_compose_yaml(ctx: StackRenderContext) -> str:
    """Render ``docker-compose.yml`` for an agent stack.

    Hand-formatted (not ``yaml.safe_dump``) for readability and deterministic
    field ordering — the shape is fixed and we never round-trip our own
    output. We *do* parse the result with ``yaml.safe_load`` at the end as a
    cheap sanity check to catch typos before SFTP'ing it to a server.
    """
    project = f"sm-agent-{ctx.agent_id}"
    stack_dir = f"{ctx.server_base_dir.rstrip('/')}/{ctx.agent_id}"
    bot_command = (
        "python -u -c "
        '"import logging,sys; logging.basicConfig(level=logging.INFO,stream=sys.stdout); '
        "from scheduler import JobScheduler; JobScheduler('/app/scheduler_config.json').run()\""
    )

    rendered = f"""# Generated by mgmt_ui — do not edit by hand.
# Project: {project}
# Stack dir: {stack_dir}
name: {project}

services:
  trading-bot:
    image: {ctx.agent_image_tag}
    container_name: sm-agent-{ctx.agent_id}-bot
    restart: unless-stopped
    environment:
      - TZ={ctx.tz}
      - OCR_SERVICE_URL={ctx.ocr_service_url}
    command: {bot_command}
    volumes:
      - ./config.ini:/app/config.ini
      - ./scheduler_config.json:/app/scheduler_config.json
      - ./locust_config.json:/app/locust_config.json
      - ./logs:/app/logs
      - ./order_results:/app/order_results
      - ./.cache:/app/.cache
      - ./trading_bot.log:/app/trading_bot.log
      - ./cache_warmup.log:/app/cache_warmup.log
"""

    # Cheap sanity check — catches a stray brace / wrong indent before we
    # SFTP this into production. Failure here is a renderer bug, not a
    # user-input bug, so an AssertionError is the right signal.
    parsed = yaml.safe_load(rendered)
    assert isinstance(parsed, dict) and "services" in parsed, (
        "render_compose_yaml produced invalid YAML"
    )
    return rendered
