"""Renderer for the per-agent ``config.ini``.

Each customer row becomes a section like::

    [a1_c2_bbi_IRO1FOLD0001]
    username = ...
    password = ...
    broker   = ...
    isin     = ...
    side     = ...

In Phase 3 the caller passes ``customers=()`` because Phase 4 (customer CRUD)
hasn't shipped yet — we still emit the ``[DEFAULT]`` header so the file is
not empty (``configparser`` dislikes truly-empty input on some platforms).
"""

from __future__ import annotations

from app.services.rendering import StackRenderContext


def render_config_ini(ctx: StackRenderContext) -> str:
    """Render ``config.ini`` from the customer rows on the context."""
    lines: list[str] = [
        "# Generated by mgmt_ui — do not edit by hand.",
        "[DEFAULT]",
        "",
    ]
    for c in ctx.customers:
        lines.append(f"[{c.section_name}]")
        lines.append(f"username = {c.username}")
        lines.append(f"password = {c.password_plain}")
        lines.append(f"broker = {c.broker}")
        lines.append(f"isin = {c.isin}")
        lines.append(f"side = {c.side}")
        lines.append("")
    return "\n".join(lines)
