"""Renderer for the per-agent ``config.ini``.

Each customer row becomes a section like::

    [a1_c2_bbi_IRO1FOLD0001]
    username = ...
    password = ...
    broker   = ...
    isin     = ...
    side     = ...

We deliberately do NOT emit a ``[DEFAULT]`` header. The original trading bot
(``SellerMarket/cache_warmup.py`` and ``locustfile_new.py``) reads
``config.sections()`` and iterates per-account configuration — a ``[DEFAULT]``
section adds no value and has caused real-world parser surprises in the bot,
so we skip it. When there are zero customers we emit just the header comment
(``configparser`` parses an empty body fine; ``config.sections()`` returns
``[]``, which is the desired "no accounts" state).
"""

from __future__ import annotations

from app.services.brokers.registry import UnknownBrokerError, family_of
from app.services.rendering import StackRenderContext


def render_config_ini(ctx: StackRenderContext) -> str:
    """Render ``config.ini`` from the customer rows on the context."""
    lines: list[str] = [
        "# Generated by mgmt_ui — do not edit by hand.",
    ]
    if not ctx.customers:
        # Zero-customer stacks get just the header so the file isn't entirely
        # blank (helps diagnostics). The bot's ``config.sections()`` returns
        # ``[]`` either way.
        lines.append("")
        return "\n".join(lines)
    for c in ctx.customers:
        lines.append("")
        lines.append(f"[{c.section_name}]")
        lines.append(f"username = {c.username}")
        lines.append(f"password = {c.password_plain}")
        lines.append(f"broker = {c.broker}")
        # Data-driven family so the bot routes to the right adapter without a
        # hardcoded enum. Additive + backward-compatible: the current bot image
        # ignores unknown keys, so emitting this can't break existing stacks.
        # Unknown / cold-cache codes default to ephoenix (the legacy behaviour).
        try:
            family = family_of(c.broker)
        except UnknownBrokerError:
            family = "ephoenix"
        lines.append(f"broker_family = {family}")
        lines.append(f"isin = {c.isin}")
        lines.append(f"side = {c.side}")
        # #110 auto-sell: emit only when armed. None AND 0 both mean "disabled"
        # (the service normalizes 0 -> None at storage, and the bot likewise
        # treats threshold <= 0 as disabled), so the truthy guard is the single
        # consistent representation. Additive — the bot ignores unknown keys.
        if c.auto_sell_threshold:
            lines.append(f"auto_sell_threshold = {c.auto_sell_threshold}")
    lines.append("")  # trailing newline
    return "\n".join(lines)
