"""Renderer for the per-agent ``.env`` file.

Notably absent: ``TELEGRAM_BOT_TOKEN``. The upstream ``simple_config_bot.py``
script tries to start a Telegram bot at import time and crashes on an empty
or invalid token. We're bypassing that script entirely via the compose
``command:`` override (see :mod:`compose_yaml`), so the env file only needs
to provide what ``cache_warmup.py`` and the scheduler actually consume.
"""

from __future__ import annotations

from app.services.rendering import StackRenderContext


def render_env(ctx: StackRenderContext) -> str:
    """Render the ``.env`` file for an agent stack."""
    return "\n".join(
        [
            "# Generated by mgmt_ui — do not edit by hand.",
            f"TZ={ctx.tz}",
            f"OCR_SERVICE_URL={ctx.ocr_service_url}",
            "",  # trailing newline
        ]
    )
