"""Unit tests for the bot config.ini [runtime] section: the settings → wire-dict
mapping (settings_store.build_runtime_section) and the renderer (config_ini).

These are pure functions (no DB) — they pin the contract that the DB-pushed
runtime overrides reach the bot in the exact wire-key names the bot reads.
"""
from __future__ import annotations

from uuid import UUID

from app.services.rendering import StackRenderContext, render_config_ini
from app.services.settings_store import DEFAULTS, build_runtime_section

FAKE_UUID = UUID("12345678-1234-5678-1234-567812345678")


def _ctx(**overrides):
    base = {
        "agent_id": FAKE_UUID,
        "server_base_dir": "/root/seller-market/agents",
        "agent_image_tag": "img:latest",
        "ocr_service_url": "http://ocr:18080",
    }
    base.update(overrides)
    return StackRenderContext(**base)


# ---------------------------------------------------------------------------
# build_runtime_section — settings → [runtime] wire dict
# ---------------------------------------------------------------------------

def test_build_runtime_strips_prefix_and_maps_aliases():
    out = build_runtime_section({
        "bot_rt_ephoenix_md_host": "newmdgw",            # != default → rendered
        "bot_rt_exir_domain": "exir2.example",           # != default → rendered
        "ocr_service_url": "http://ocr:18080, http://ocr2:18080",
        "bot_market_data_url": "http://5.10.248.55:8077",
        "unrelated_setting": "ignored",
    })
    assert out["ephoenix_md_host"] == "newmdgw"
    assert out["exir_domain"] == "exir2.example"
    # the two existing settings flow in under their bot wire names
    assert out["ocr_service_url"] == "http://ocr:18080, http://ocr2:18080"
    assert out["market_data_url"] == "http://5.10.248.55:8077"
    # non bot_rt_ / non-aliased settings never leak into [runtime]
    assert "unrelated_setting" not in out
    assert "bot_rt_ephoenix_md_host" not in out


def test_build_runtime_omits_empty_and_default_values():
    out = build_runtime_section({
        "bot_rt_ephoenix_md_host": "",                   # empty → omitted
        "ocr_service_url": "",
        "bot_market_data_url": "",                        # default empty → omitted
        "bot_rt_ephoenix_domain": "ephoenix.ir",         # == default → omitted
        "bot_rt_exir_domain": "exir2.example",           # != default → kept
    })
    assert out == {"exir_domain": "exir2.example"}


def test_build_runtime_all_defaults_renders_nothing():
    # The whole DEFAULTS set unchanged ⇒ empty [runtime] ⇒ byte-identical config.
    assert build_runtime_section(dict(DEFAULTS)) == {}


def test_build_runtime_escape_hatch_keys_pass_through():
    out = build_runtime_section({
        "bot_rt_endpoint_ib_order": "https://custom/x",
        "bot_rt_rlc_base_url": "https://core2//Handler",
    })
    assert out["endpoint_ib_order"] == "https://custom/x"
    assert out["rlc_base_url"] == "https://core2//Handler"


def test_defaults_carry_the_disaster_set():
    # Every first-class runtime key ships a default equal to the current
    # hardcoded value, so behaviour is unchanged until edited.
    assert DEFAULTS["bot_rt_ephoenix_domain"] == "ephoenix.ir"
    assert DEFAULTS["bot_rt_ephoenix_md_host"] == "marketdatagw"
    assert DEFAULTS["bot_rt_ib_domain"] == "ibtrader.ir"
    assert DEFAULTS["bot_rt_ib_md_host"] == "mdapi"
    assert DEFAULTS["bot_rt_ib_portfolio_shard"] == "api8"
    assert DEFAULTS["bot_rt_exir_domain"] == "exirbroker.com"
    assert DEFAULTS["bot_rt_exir_fallback_buy_fee"] == "0.005"
    assert DEFAULTS["bot_rt_auto_sell_window"] == "09:00-12:30"
    # stored as the float repr so an unchanged Save round-trips to "no change"
    assert DEFAULTS["bot_rt_auto_sell_confirm_secs"] == "5.0"


# ---------------------------------------------------------------------------
# render_config_ini — the [runtime] section
# ---------------------------------------------------------------------------

def test_runtime_section_omitted_when_empty():
    # No runtime dict → byte-identical to the legacy header+sentinel output.
    out = render_config_ini(_ctx())
    assert "[runtime]" not in out
    assert out == (
        "# Generated by mgmt_ui — do not edit by hand.\n"
        "\n"
        "# auto-sell-config-end\n"
    )


def test_runtime_section_rendered_before_sentinel_sorted():
    out = render_config_ini(_ctx(runtime={
        "ephoenix_md_host": "newmdgw",
        "ephoenix_domain": "ephoenix.ir",
    }))
    assert "[runtime]" in out
    # deterministic sorted key order
    assert out.index("ephoenix_domain = ephoenix.ir") < out.index("ephoenix_md_host = newmdgw")
    # section sits before the trailing sentinel
    assert out.index("[runtime]") < out.index("# auto-sell-config-end")


def test_runtime_section_percent_escaped():
    # A literal % is %%-escaped so the bot's interpolating ConfigParser readers
    # (which parse the WHOLE file) don't choke.
    out = render_config_ini(_ctx(runtime={"endpoint_ib_order": "https://x/y?a=%20b"}))
    assert "endpoint_ib_order = https://x/y?a=%%20b" in out


def test_runtime_section_with_customers_precedes_sections():
    cust = type("C", (), {})()  # not used; use real CustomerRow via render
    from app.services.rendering import CustomerRow
    c = CustomerRow("sec_one", "u1", "p1", "bbi", "IRO1A", 1)
    out = render_config_ini(_ctx(customers=(c,), runtime={"ephoenix_md_host": "x"}))
    assert out.index("[runtime]") < out.index("[sec_one]")
    assert out.index("[sec_one]") < out.index("# auto-sell-config-end")
