"""Golden-file tests for :mod:`app.services.rendering`.

Each renderer must produce a deterministic, byte-identical output for a
fixed input — these tests pin that contract so any drift is loud.
"""

from __future__ import annotations

import json
from uuid import UUID

import pytest
import yaml

from app.services.rendering import (
    CustomerRow,
    LocustConfigRow,
    SchedulerJobRow,
    StackRenderContext,
    render_compose_yaml,
    render_config_ini,
    render_env,
    render_locust_config,
    render_scheduler_config,
)

# A stable fake UUID so YAML output is deterministic across runs.
FAKE_UUID = UUID("12345678-1234-5678-1234-567812345678")
AGENT_IMAGE = "ghcr.io/pesahm/seller-market-scheduler:latest"
OCR_URL = "http://5.10.248.55:18080"
BASE_DIR = "/root/seller-market/agents"


def _ctx(**overrides: object) -> StackRenderContext:
    """Build a baseline StackRenderContext, optionally overriding fields."""
    defaults: dict[str, object] = {
        "agent_id": FAKE_UUID,
        "server_base_dir": BASE_DIR,
        "agent_image_tag": AGENT_IMAGE,
        "ocr_service_url": OCR_URL,
    }
    defaults.update(overrides)
    return StackRenderContext(**defaults)  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# compose_yaml
# ---------------------------------------------------------------------------


def test_compose_yaml_shape() -> None:
    out = render_compose_yaml(_ctx())

    assert f"name: sm-agent-{FAKE_UUID}" in out
    assert f"image: {AGENT_IMAGE}" in out
    assert f"OCR_SERVICE_URL={OCR_URL}" in out

    expected_cmd = (
        "python -u -c "
        '"import logging,sys; logging.basicConfig(level=logging.INFO,stream=sys.stdout); '
        "from scheduler import JobScheduler; JobScheduler('/app/scheduler_config.json').run()\""
    )
    assert expected_cmd in out

    # Plan invariants: no host-port mapping, no telegram leakage.
    assert "ports:" not in out
    assert "TELEGRAM_BOT_TOKEN" not in out

    # Round-trip parse — the renderer asserts this internally, but we
    # reassert here so a regression in the renderer is also caught here.
    parsed = yaml.safe_load(out)
    assert isinstance(parsed, dict)
    assert "services" in parsed
    assert "trading-bot" in parsed["services"]
    assert parsed["name"] == f"sm-agent-{FAKE_UUID}"


def test_compose_yaml_no_telegram_no_ocr_sidecar() -> None:
    """Belt-and-braces: scan for forbidden strings case-insensitively."""
    out = render_compose_yaml(_ctx()).lower()

    forbidden = [
        "telegram",
        # The shared OCR service should be referenced by URL only; no
        # `ocr:` or `ocr-service:` sibling service.
        "\n  ocr:",
        "\n  ocr-service:",
        "ports:",
    ]
    for needle in forbidden:
        assert needle not in out, f"compose YAML contains forbidden token: {needle!r}"


def test_deterministic_compose_yaml() -> None:
    """Two renders of the same context must be byte-identical."""
    ctx = _ctx()
    assert render_compose_yaml(ctx) == render_compose_yaml(ctx)


def test_compose_yaml_trims_trailing_slash_on_base_dir() -> None:
    a = render_compose_yaml(_ctx(server_base_dir="/root/seller-market/agents"))
    b = render_compose_yaml(_ctx(server_base_dir="/root/seller-market/agents/"))
    assert a == b


# ---------------------------------------------------------------------------
# env_file
# ---------------------------------------------------------------------------


def test_env_no_telegram_token() -> None:
    out = render_env(_ctx())
    assert "TELEGRAM" not in out.upper()
    assert "TZ=Asia/Tehran" in out
    assert f"OCR_SERVICE_URL={OCR_URL}" in out
    # Trailing newline so POSIX tooling is happy.
    assert out.endswith("\n")


def test_env_custom_tz() -> None:
    out = render_env(_ctx(tz="UTC"))
    assert "TZ=UTC" in out


# ---------------------------------------------------------------------------
# config_ini
# ---------------------------------------------------------------------------


def test_config_ini_empty_when_no_customers() -> None:
    out = render_config_ini(_ctx())
    # Header + DEFAULT section + trailing blank line.
    expected = "# Generated by mgmt_ui — do not edit by hand.\n[DEFAULT]\n"
    assert out == expected


def test_config_ini_renders_customer_sections() -> None:
    cust = CustomerRow(
        section_name="a1_c2_bbi_IRO1FOLD0001",
        username="user1",
        password_plain="hunter2",
        broker="bbi",
        isin="IRO1FOLD0001",
        side=1,
    )
    out = render_config_ini(_ctx(customers=(cust,)))

    assert "[a1_c2_bbi_IRO1FOLD0001]" in out
    assert "username = user1" in out
    assert "password = hunter2" in out
    assert "broker = bbi" in out
    assert "isin = IRO1FOLD0001" in out
    assert "side = 1" in out
    # All five keys present.
    for key in ("username", "password", "broker", "isin", "side"):
        assert f"{key} = " in out


def test_config_ini_renders_multiple_customers() -> None:
    customers = (
        CustomerRow("sec_one", "u1", "p1", "bbi", "IRO1A", 1),
        CustomerRow("sec_two", "u2", "p2", "ayandeh", "IRO1B", 2),
    )
    out = render_config_ini(_ctx(customers=customers))
    assert "[sec_one]" in out
    assert "[sec_two]" in out
    assert out.index("[sec_one]") < out.index("[sec_two]")


# ---------------------------------------------------------------------------
# scheduler_config
# ---------------------------------------------------------------------------


def test_scheduler_config_default_disabled() -> None:
    out = render_scheduler_config(_ctx())
    parsed = json.loads(out)
    assert parsed == {"enabled": False, "jobs": []}
    # Trailing newline for POSIX hygiene.
    assert out.endswith("\n")


def test_scheduler_config_jobs_round_trip() -> None:
    jobs = (
        SchedulerJobRow(
            name="cache_warmup",
            time="08:00:00",
            enabled=True,
            command="python cache_warmup.py",
        ),
        SchedulerJobRow(
            name="run_trading",
            time="09:00:00",
            enabled=False,
            command="python trading_bot.py --section a1_c2_bbi_IRO1FOLD0001",
        ),
    )
    out = render_scheduler_config(_ctx(scheduler_jobs=jobs, scheduler_enabled=True))

    expected = (
        json.dumps(
            {
                "enabled": True,
                "jobs": [
                    {
                        "name": "cache_warmup",
                        "time": "08:00:00",
                        "command": "python cache_warmup.py",
                        "enabled": True,
                    },
                    {
                        "name": "run_trading",
                        "time": "09:00:00",
                        "command": "python trading_bot.py --section a1_c2_bbi_IRO1FOLD0001",
                        "enabled": False,
                    },
                ],
            },
            indent=2,
        )
        + "\n"
    )
    assert out == expected


# ---------------------------------------------------------------------------
# locust_config
# ---------------------------------------------------------------------------


def test_locust_config_defaults() -> None:
    out = render_locust_config(_ctx())
    parsed = json.loads(out)
    assert parsed == {
        "locust": {
            "users": 10,
            "spawn_rate": 10,
            "run_time": "120s",
            "host": "https://abc.com",
            "processes": 1,
        }
    }
    assert out.endswith("\n")


def test_locust_config_override() -> None:
    override = LocustConfigRow(
        users=50,
        spawn_rate=5,
        run_time="600s",
        host="https://load.example.com",
        processes=4,
    )
    out = render_locust_config(_ctx(locust=override))
    parsed = json.loads(out)
    assert parsed == {
        "locust": {
            "users": 50,
            "spawn_rate": 5,
            "run_time": "600s",
            "host": "https://load.example.com",
            "processes": 4,
        }
    }


# ---------------------------------------------------------------------------
# Smoke: re-exports are wired correctly.
# ---------------------------------------------------------------------------


def test_module_exports() -> None:
    """The public surface advertised in ``__init__`` must actually resolve."""
    import app.services.rendering as rendering

    for name in (
        "render_compose_yaml",
        "render_env",
        "render_config_ini",
        "render_scheduler_config",
        "render_locust_config",
        "StackRenderContext",
        "CustomerRow",
        "SchedulerJobRow",
        "LocustConfigRow",
    ):
        assert hasattr(rendering, name), f"missing re-export: {name}"


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(pytest.main([__file__, "-v"]))
